build_from:
  amd64: docker.n8n.io/n8nio/n8n:2.16.1
  aarch64: docker.n8n.io/n8nio/n8n:2.16.1
labels:
  org.opencontainers.image.title: "n8n Home Assistant Addon"
  org.opencontainers.image.description: "n8n workflow automation for Home Assistant"
  org.opencontainers.image.source: "https://github.com/momohteks/hassio-n8n"
  org.opencontainers.image.licenses: "Apache-2.0"
